using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Web;

/// <summary>
/// Task 15, Sections E/G/H/I: reading, manually editing, and swapping placed timetable
/// entries, plus the read-only Faculty/Class/Room timetable views.
/// </summary>
public static class TimetableHelper
{
    public static DataTable GetUnresolved(int academicYearId, int divisionId)
    {
        return DBHelper.ExecuteQuery(@"
            SELECT u.Reason, s.SubjectName, u.RunDate FROM dbo.TT_UnresolvedRequirements u
            INNER JOIN dbo.TT_Subjects s ON u.SubjectID = s.SubjectID
            WHERE u.AcademicYearID=@AY AND u.DivisionID=@D ORDER BY u.RunDate",
            new SqlParameter("@AY", academicYearId), new SqlParameter("@D", divisionId));
    }

    /// <summary>Full grid of entries for one division: DayID/PeriodID plus display columns.</summary>
    public static DataTable GetDivisionTimetable(int academicYearId, int divisionId)
    {
        return DBHelper.ExecuteQuery(@"
            SELECT t.EntryID, t.DayID, w.DayName, t.PeriodID, p.PeriodNumber, p.Label AS PeriodLabel,
                   p.StartTime, p.EndTime, t.SubjectID, s.SubjectName, s.SubjectCode, s.SubjectType,
                   t.FacultyID, f.FacultyName, t.RoomID, r.RoomNumber, r.RoomType, t.BatchLabel, t.IsAutoGenerated
            FROM dbo.TT_Timetable t
            INNER JOIN dbo.TT_WorkingDays w ON t.DayID = w.DayID
            INNER JOIN dbo.TT_Periods p ON t.PeriodID = p.PeriodID
            INNER JOIN dbo.TT_Subjects s ON t.SubjectID = s.SubjectID
            INNER JOIN dbo.TT_Faculty f ON t.FacultyID = f.FacultyID
            INNER JOIN dbo.TT_Rooms r ON t.RoomID = r.RoomID
            WHERE t.AcademicYearID=@AY AND t.DivisionID=@D
            ORDER BY w.DayOrder, p.PeriodNumber",
            new SqlParameter("@AY", academicYearId), new SqlParameter("@D", divisionId));
    }

    public static DataTable GetFacultyTimetable(int facultyId)
    {
        return DBHelper.ExecuteQuery(@"
            SELECT t.EntryID, w.DayName, w.DayOrder, p.PeriodNumber, p.Label AS PeriodLabel, p.StartTime, p.EndTime,
                   s.SubjectName, s.SubjectCode, d.DivisionName, c.CourseName, d.YearSemester, r.RoomNumber, t.BatchLabel
            FROM dbo.TT_Timetable t
            INNER JOIN dbo.TT_WorkingDays w ON t.DayID = w.DayID
            INNER JOIN dbo.TT_Periods p ON t.PeriodID = p.PeriodID
            INNER JOIN dbo.TT_Subjects s ON t.SubjectID = s.SubjectID
            INNER JOIN dbo.TT_Divisions d ON t.DivisionID = d.DivisionID
            INNER JOIN dbo.Courses c ON d.CourseID = c.CourseID
            INNER JOIN dbo.TT_Rooms r ON t.RoomID = r.RoomID
            WHERE t.FacultyID=@F ORDER BY w.DayOrder, p.PeriodNumber",
            new SqlParameter("@F", facultyId));
    }

    public static DataTable GetRoomUtilization(int roomId)
    {
        return DBHelper.ExecuteQuery(@"
            SELECT t.EntryID, w.DayName, w.DayOrder, p.PeriodNumber, p.Label AS PeriodLabel,
                   s.SubjectName, d.DivisionName, c.CourseName, f.FacultyName, t.BatchLabel
            FROM dbo.TT_Timetable t
            INNER JOIN dbo.TT_WorkingDays w ON t.DayID = w.DayID
            INNER JOIN dbo.TT_Periods p ON t.PeriodID = p.PeriodID
            INNER JOIN dbo.TT_Subjects s ON t.SubjectID = s.SubjectID
            INNER JOIN dbo.TT_Divisions d ON t.DivisionID = d.DivisionID
            INNER JOIN dbo.Courses c ON d.CourseID = c.CourseID
            INNER JOIN dbo.TT_Faculty f ON t.FacultyID = f.FacultyID
            WHERE t.RoomID=@R ORDER BY w.DayOrder, p.PeriodNumber",
            new SqlParameter("@R", roomId));
    }

    /// <summary>Renders a division's timetable grid (rows=periods, columns=days) as an HTML
    /// table. Shared by the Generate preview, the read-only Class Timetable view, and the
    /// manual Editor (which further wraps each cell in an edit/swap control).</summary>
    public static string RenderGridHtml(DataTable entries, bool showEntryIds)
    {
        DataTable days = TimetableSetupHelper.GetWorkingDays();
        DataTable periods = TimetableSetupHelper.GetTeachingPeriods();

        var cellLookup = new Dictionary<string, DataRow>();
        foreach (DataRow row in entries.Rows)
            cellLookup[row["DayID"] + "_" + row["PeriodID"]] = row;

        var sb = new System.Text.StringBuilder();
        sb.Append("<div class='table-responsive'><table class='table table-bordered tt-grid mb-0'><thead><tr><th>Period \\ Day</th>");
        foreach (DataRow day in days.Rows)
        {
            if (!Convert.ToBoolean(day["IsWorkingDay"])) continue;
            sb.AppendFormat("<th>{0}</th>", day["DayName"]);
        }
        sb.Append("</tr></thead><tbody>");

        foreach (DataRow period in periods.Rows)
        {
            int periodId = Convert.ToInt32(period["PeriodID"]);
            sb.AppendFormat("<tr><td class='fw-semibold'>{0}<br/><small>{1}-{2}</small></td>", period["Label"], period["StartTime"], period["EndTime"]);
            foreach (DataRow day in days.Rows)
            {
                if (!Convert.ToBoolean(day["IsWorkingDay"])) continue;
                int dayId = Convert.ToInt32(day["DayID"]);
                DataRow cell;
                if (cellLookup.TryGetValue(dayId + "_" + periodId, out cell))
                {
                    sb.Append("<td>");
                    sb.Append("<div class='tt-cell'>");
                    sb.AppendFormat("<span class='sub'>{0}</span>", HttpUtility.HtmlEncode(cell["SubjectName"].ToString()));
                    sb.AppendFormat("<span class='meta'>{0} &middot; {1}{2}</span>",
                        HttpUtility.HtmlEncode(cell["FacultyName"].ToString()),
                        HttpUtility.HtmlEncode(cell["RoomNumber"].ToString()),
                        string.IsNullOrEmpty(cell["BatchLabel"].ToString()) ? "" : " (" + cell["BatchLabel"] + ")");
                    if (showEntryIds) sb.AppendFormat("<span class='meta'>#{0}</span>", cell["EntryID"]);
                    sb.Append("</div></td>");
                }
                else
                {
                    sb.Append("<td class='tt-empty'>&mdash;</td>");
                }
            }
            sb.Append("</tr>");
        }
        sb.Append("</tbody></table></div>");
        return sb.ToString();
    }

    public static DataRow GetEntry(int entryId)
    {
        DataTable dt = DBHelper.ExecuteQuery("SELECT * FROM dbo.TT_Timetable WHERE EntryID=@ID", new SqlParameter("@ID", entryId));
        return dt.Rows.Count == 0 ? null : dt.Rows[0];
    }

    /// <summary>Section G — manual edit: validates before writing, exactly like the generator.
    /// Returns an empty conflict list on success (and the row is written); a non-empty list
    /// means nothing was changed.</summary>
    public static List<string> TryMoveEntry(int entryId, int newDayId, int newPeriodId, int newFacultyId, int newRoomId)
    {
        DataRow entry = GetEntry(entryId);
        if (entry == null) return new List<string> { "Entry not found." };

        int academicYearId = Convert.ToInt32(entry["AcademicYearID"]);
        int divisionId = Convert.ToInt32(entry["DivisionID"]);
        int subjectId = Convert.ToInt32(entry["SubjectID"]);
        string batchLabel = entry["BatchLabel"].ToString();

        var conflicts = TimetableConflictDetector.CheckConflicts(
            academicYearId, divisionId, newDayId, newPeriodId, subjectId, newFacultyId, newRoomId, batchLabel, entryId);

        if (conflicts.Count > 0) return conflicts;

        DBHelper.ExecuteNonQuery(@"
            UPDATE dbo.TT_Timetable SET DayID=@Day, PeriodID=@P, FacultyID=@F, RoomID=@R,
                   IsAutoGenerated=0, ModifiedDate=GETDATE() WHERE EntryID=@ID",
            new SqlParameter("@Day", newDayId), new SqlParameter("@P", newPeriodId),
            new SqlParameter("@F", newFacultyId), new SqlParameter("@R", newRoomId), new SqlParameter("@ID", entryId));

        return conflicts;
    }

    /// <summary>Section H — swap: two entries exchange (Day, Period). Each resulting placement
    /// is validated against every OTHER existing entry before either row is written, so a
    /// swap that would create a fresh conflict is rejected with the reason(s) and nothing changes.</summary>
    public static List<string> TrySwapEntries(int entryIdA, int entryIdB)
    {
        DataRow a = GetEntry(entryIdA);
        DataRow b = GetEntry(entryIdB);
        if (a == null || b == null) return new List<string> { "One or both entries were not found." };

        int aDay = Convert.ToInt32(a["DayID"]), aPeriod = Convert.ToInt32(a["PeriodID"]);
        int bDay = Convert.ToInt32(b["DayID"]), bPeriod = Convert.ToInt32(b["PeriodID"]);

        var reasons = new List<string>();

        // Validate A moving into B's old slot, and B moving into A's old slot — each excluding
        // itself AND (implicitly, since we haven't written yet) not clashing with the other
        // because the other hasn't landed there until both checks pass.
        var conflictsForA = TimetableConflictDetector.CheckConflicts(
            Convert.ToInt32(a["AcademicYearID"]), Convert.ToInt32(a["DivisionID"]), bDay, bPeriod,
            Convert.ToInt32(a["SubjectID"]), Convert.ToInt32(a["FacultyID"]), Convert.ToInt32(a["RoomID"]),
            a["BatchLabel"].ToString(), entryIdA);
        // The clash this check would report against B's original slot is expected (that's the swap) —
        // filter out a "conflict" that is solely B's own EntryID by re-running with B excluded too.
        conflictsForA = FilterSelfSwapNoise(conflictsForA, entryIdB, Convert.ToInt32(a["AcademicYearID"]),
            Convert.ToInt32(a["DivisionID"]), bDay, bPeriod, Convert.ToInt32(a["SubjectID"]),
            Convert.ToInt32(a["FacultyID"]), Convert.ToInt32(a["RoomID"]), a["BatchLabel"].ToString(), entryIdA);

        var conflictsForB = TimetableConflictDetector.CheckConflicts(
            Convert.ToInt32(b["AcademicYearID"]), Convert.ToInt32(b["DivisionID"]), aDay, aPeriod,
            Convert.ToInt32(b["SubjectID"]), Convert.ToInt32(b["FacultyID"]), Convert.ToInt32(b["RoomID"]),
            b["BatchLabel"].ToString(), entryIdB);
        conflictsForB = FilterSelfSwapNoise(conflictsForB, entryIdA, Convert.ToInt32(b["AcademicYearID"]),
            Convert.ToInt32(b["DivisionID"]), aDay, aPeriod, Convert.ToInt32(b["SubjectID"]),
            Convert.ToInt32(b["FacultyID"]), Convert.ToInt32(b["RoomID"]), b["BatchLabel"].ToString(), entryIdB);

        reasons.AddRange(conflictsForA);
        reasons.AddRange(conflictsForB);
        if (reasons.Count > 0) return reasons;

        DBHelper.ExecuteNonQuery(
            "UPDATE dbo.TT_Timetable SET DayID=@D, PeriodID=@P, IsAutoGenerated=0, ModifiedDate=GETDATE() WHERE EntryID=@ID",
            new SqlParameter("@D", bDay), new SqlParameter("@P", bPeriod), new SqlParameter("@ID", entryIdA));
        DBHelper.ExecuteNonQuery(
            "UPDATE dbo.TT_Timetable SET DayID=@D, PeriodID=@P, IsAutoGenerated=0, ModifiedDate=GETDATE() WHERE EntryID=@ID",
            new SqlParameter("@D", aDay), new SqlParameter("@P", aPeriod), new SqlParameter("@ID", entryIdB));

        return reasons; // empty = success
    }

    /// <summary>Re-checks a candidate placement with the counterpart entry ALSO excluded, so
    /// a two-way swap isn't rejected purely because each side currently sits where the other
    /// is heading. Any conflict that survives with both excluded is a genuine, reportable clash.</summary>
    private static List<string> FilterSelfSwapNoise(List<string> original, int otherExcludeId,
        int academicYearId, int divisionId, int dayId, int periodId, int subjectId, int facultyId, int roomId,
        string batchLabel, int selfExcludeId)
    {
        if (original.Count == 0) return original;

        // Re-run the check purely against rows other than A and B to see if the conflict is real.
        DataTable clashes = DBHelper.ExecuteQuery(@"
            SELECT COUNT(*) AS Cnt FROM dbo.TT_Timetable t
            WHERE t.DayID=@Day AND t.PeriodID=@P AND t.EntryID NOT IN (@Self,@Other)
              AND (t.FacultyID=@F OR t.RoomID=@R OR (t.DivisionID=@Div AND t.BatchLabel=@BL))",
            new SqlParameter("@Day", dayId), new SqlParameter("@P", periodId),
            new SqlParameter("@Self", selfExcludeId), new SqlParameter("@Other", otherExcludeId),
            new SqlParameter("@F", facultyId), new SqlParameter("@R", roomId),
            new SqlParameter("@Div", divisionId), new SqlParameter("@BL", batchLabel));

        int genuineClashCount = Convert.ToInt32(clashes.Rows[0]["Cnt"]);
        if (genuineClashCount == 0)
        {
            // Every reason in "original" was noise from the counterpart entry — drop faculty/room/class
            // conflict reasons but keep any non-clash reasons (capacity, lab-type, availability, break/day).
            var kept = new List<string>();
            foreach (string reason in original)
            {
                if (reason.StartsWith("Faculty conflict") || reason.StartsWith("Room conflict") || reason.StartsWith("Class conflict"))
                    continue;
                kept.Add(reason);
            }
            return kept;
        }
        return original;
    }
}
