using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;

/// <summary>
/// Task 15, Section E/F: automatic timetable generator. A constructive/greedy placer with
/// backtracking-by-retry: for every (division, subject) it needs to place WeeklyHours periods,
/// it tries each candidate (day, period, faculty, room) combination, validates it through
/// TimetableConflictDetector (the same validator the manual editor uses, so generated and
/// hand-edited slots are held to one standard), and commits the first conflict-free option.
/// Anything it cannot place after exhausting candidates is logged to
/// TT_UnresolvedRequirements instead of silently dropped, per the brief's Section F.
/// </summary>
public static class TimetableGenerationEngine
{
    public class GenerationResult
    {
        public int PlacedCount;
        public List<string> UnresolvedMessages = new List<string>();
    }

    /// <summary>Generates (or regenerates) the timetable for one division. Existing
    /// auto-generated entries for the division are cleared first; manually-edited entries
    /// (IsAutoGenerated = 0) are left untouched and treated as fixed constraints.</summary>
    public static GenerationResult GenerateForDivision(int academicYearId, int divisionId, string generatedBy)
    {
        var result = new GenerationResult();

        DBHelper.ExecuteNonQuery(
            "DELETE FROM dbo.TT_Timetable WHERE DivisionID=@D AND AcademicYearID=@AY AND IsAutoGenerated=1",
            new SqlParameter("@D", divisionId), new SqlParameter("@AY", academicYearId));
        DBHelper.ExecuteNonQuery("DELETE FROM dbo.TT_UnresolvedRequirements WHERE DivisionID=@D AND AcademicYearID=@AY",
            new SqlParameter("@D", divisionId), new SqlParameter("@AY", academicYearId));

        DataRow division = TimetableSetupHelper.GetDivision(divisionId);
        if (division == null) { result.UnresolvedMessages.Add("Division not found."); return result; }

        DataTable days = TimetableSetupHelper.GetWorkingDays();
        DataTable periods = TimetableSetupHelper.GetTeachingPeriods();
        int maxPerDay = TimetableSetupHelper.GetMaxClassesPerDay();

        DataTable subjects = TimetableSetupHelper.GetSubjectsForDivision(divisionId);
        // Longest/hardest-to-place subjects first (more weekly hours, then Practical before
        // Theory since labs are the scarcer resource) — a standard constructive-scheduling heuristic.
        var orderedSubjects = subjects.Rows.Cast<DataRow>()
            .OrderByDescending(r => Convert.ToInt32(r["WeeklyHours"]))
            .ThenBy(r => r["SubjectType"].ToString() == "Practical" ? 0 : 1)
            .ToList();

        // Track how many periods are already used per (day) for this division in this run,
        // to respect MaxClassesPerDay even though the DB check happens per-slot.
        var dayLoad = new Dictionary<int, int>();
        foreach (DataRow d in days.Rows) dayLoad[Convert.ToInt32(d["DayID"])] = 0;

        foreach (DataRow subject in orderedSubjects)
        {
            int subjectId = Convert.ToInt32(subject["SubjectID"]);
            string subjectType = subject["SubjectType"].ToString();
            int weeklyHours = Convert.ToInt32(subject["WeeklyHours"]);

            DataTable facultyOptions = DBHelper.ExecuteQuery(@"
                SELECT DISTINCT fs.FacultyID FROM dbo.TT_FacultySubjects fs
                WHERE fs.SubjectID=@S AND fs.DivisionID=@D",
                new SqlParameter("@S", subjectId), new SqlParameter("@D", divisionId));

            if (facultyOptions.Rows.Count == 0)
            {
                result.UnresolvedMessages.Add(LogUnresolved(academicYearId, divisionId, subjectId,
                    string.Format("No faculty assigned to teach {0} for this division.", subject["SubjectName"])));
                continue;
            }

            string requiredRoomType = subjectType == "Practical" ? "Laboratory" : "Classroom";
            DataTable roomOptions = DBHelper.ExecuteQuery(
                "SELECT RoomID, Capacity FROM dbo.TT_Rooms WHERE RoomType=@T AND IsActive=1 ORDER BY Capacity",
                new SqlParameter("@T", requiredRoomType));

            if (roomOptions.Rows.Count == 0)
            {
                result.UnresolvedMessages.Add(LogUnresolved(academicYearId, divisionId, subjectId,
                    string.Format("No active {0} available for {1}.", requiredRoomType.ToLower(), subject["SubjectName"])));
                continue;
            }

            int placedForThisSubject = 0;
            for (int attempt = 0; attempt < weeklyHours; attempt++)
            {
                bool placed = false;

                foreach (DataRow day in days.Rows)
                {
                    if (!Convert.ToBoolean(day["IsWorkingDay"])) continue;
                    int dayId = Convert.ToInt32(day["DayID"]);
                    if (dayLoad[dayId] >= maxPerDay) continue;

                    foreach (DataRow period in periods.Rows)
                    {
                        int periodId = Convert.ToInt32(period["PeriodID"]);

                        foreach (DataRow fac in facultyOptions.Rows)
                        {
                            int facultyId = Convert.ToInt32(fac["FacultyID"]);
                            foreach (DataRow room in roomOptions.Rows)
                            {
                                int roomId = Convert.ToInt32(room["RoomID"]);

                                var conflicts = TimetableConflictDetector.CheckConflicts(
                                    academicYearId, divisionId, dayId, periodId, subjectId, facultyId, roomId, "", -1);

                                if (conflicts.Count == 0)
                                {
                                    DBHelper.ExecuteInsertReturnId(@"
                                        INSERT INTO dbo.TT_Timetable
                                            (AcademicYearID, DivisionID, DayID, PeriodID, SubjectID, FacultyID, RoomID, BatchLabel, IsAutoGenerated)
                                        VALUES (@AY,@D,@Day,@P,@S,@F,@R,'',1)",
                                        new SqlParameter("@AY", academicYearId), new SqlParameter("@D", divisionId),
                                        new SqlParameter("@Day", dayId), new SqlParameter("@P", periodId),
                                        new SqlParameter("@S", subjectId), new SqlParameter("@F", facultyId), new SqlParameter("@R", roomId));

                                    dayLoad[dayId]++;
                                    placedForThisSubject++;
                                    placed = true;
                                    result.PlacedCount++;
                                    break;
                                }
                            }
                            if (placed) break;
                        }
                        if (placed) break;
                    }
                    if (placed) break;
                }

                if (!placed)
                {
                    result.UnresolvedMessages.Add(LogUnresolved(academicYearId, divisionId, subjectId,
                        string.Format("Could only place {0} of {1} weekly period(s) for {2} — no conflict-free slot left.",
                            placedForThisSubject, weeklyHours, subject["SubjectName"])));
                    break;
                }
            }
        }

        AppLogger.Info("TimetableGenerationEngine",
            string.Format("Generated timetable for DivisionID={0}, AcademicYearID={1} by {2}: {3} periods placed, {4} unresolved.",
                divisionId, academicYearId, generatedBy, result.PlacedCount, result.UnresolvedMessages.Count));

        return result;
    }

    private static string LogUnresolved(int academicYearId, int divisionId, int subjectId, string reason)
    {
        DBHelper.ExecuteNonQuery(
            "INSERT INTO dbo.TT_UnresolvedRequirements (AcademicYearID, DivisionID, SubjectID, Reason) VALUES (@AY,@D,@S,@R)",
            new SqlParameter("@AY", academicYearId), new SqlParameter("@D", divisionId),
            new SqlParameter("@S", subjectId), new SqlParameter("@R", reason));
        return reason;
    }
}
