//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    // Task 8: AdminLogin.aspx has no runat="server" controls — the login form is a plain
    // HTML <form method="get"> so the browser submits it as a standard GET request. Nothing
    // to declare here; ErrorMessage / PostedUsername are plain C# properties on the code-behind.
    public partial class AdminLogin
    {
    }
}
