//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class BulkRegister
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMsg;
        protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
        protected global::System.Web.UI.WebControls.Panel pnlWarningMsg;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.HiddenField hdnFullMobile;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.TextBox txtDOB;
        protected global::System.Web.UI.UpdatePanel upLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlCountry;
        protected global::System.Web.UI.WebControls.DropDownList ddlState;
        protected global::System.Web.UI.WebControls.DropDownList ddlDistrict;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.Button btnAddRecord;
        protected global::System.Web.UI.WebControls.LinkButton btnDownloadTemplate;
        protected global::System.Web.UI.WebControls.FileUpload fuBulkFile;
        protected global::System.Web.UI.WebControls.Button btnPreviewFile;
        protected global::System.Web.UI.WebControls.Panel pnlImportPreview;
        protected global::System.Web.UI.WebControls.Panel pnlImportSummary;
        protected global::System.Web.UI.WebControls.GridView gvImportPreview;
        protected global::System.Web.UI.WebControls.Button btnCancelImport;
        protected global::System.Web.UI.WebControls.Button btnImportValidRows;
        protected global::System.Web.UI.WebControls.Label lblTempCount;
        protected global::System.Web.UI.WebControls.GridView gvTemp;
        protected global::System.Web.UI.WebControls.Button btnClearAll;
        protected global::System.Web.UI.WebControls.Button btnSaveAll;
    }
}
