//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class ClassTimetableView
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlDivision;
        protected global::System.Web.UI.WebControls.Button btnView;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlGrid;
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Literal litGrid;
    }
}
