//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMsg;
        protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgProfilePhoto;
        protected global::System.Web.UI.WebControls.Literal litStudentId;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litMobile;
        protected global::System.Web.UI.WebControls.Literal litGender;
        protected global::System.Web.UI.WebControls.Literal litDOB;
        protected global::System.Web.UI.WebControls.Literal litCountry;
        protected global::System.Web.UI.WebControls.Literal litState;
        protected global::System.Web.UI.WebControls.Literal litDistrict;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Literal litRegisteredOn;
        protected global::System.Web.UI.WebControls.Literal litLastLogin;
        protected global::System.Web.UI.WebControls.Panel pnlNoFees;
        protected global::System.Web.UI.WebControls.Literal litNoFeesMessage;
        protected global::System.Web.UI.WebControls.Panel pnlFeeSummary;
        protected global::System.Web.UI.WebControls.Literal litTotalPayable;
        protected global::System.Web.UI.WebControls.Literal litAmountPaid;
        protected global::System.Web.UI.WebControls.Literal litOutstanding;
        protected global::System.Web.UI.WebControls.Literal litLateFee;
        protected global::System.Web.UI.WebControls.Literal litDiscount;
        protected global::System.Web.UI.WebControls.Literal litNetPayable;
        protected global::System.Web.UI.WebControls.Literal litPaymentStatus;
        protected global::System.Web.UI.WebControls.GridView gvMyFees;
        protected global::System.Web.UI.WebControls.GridView gvMyPayments;
        protected global::System.Web.UI.WebControls.TextBox txtEditStudentId;
        protected global::System.Web.UI.WebControls.TextBox txtEditEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEditFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEditMobile;
        protected global::System.Web.UI.WebControls.HiddenField hdnEditFullMobile;
        protected global::System.Web.UI.UpdatePanel upEditLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditCountry;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditState;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditDistrict;
        protected global::System.Web.UI.WebControls.TextBox txtEditAddress;
        protected global::System.Web.UI.HtmlControls.HtmlImage photoPreviewEdit;
        protected global::System.Web.UI.WebControls.FileUpload fuEditPhoto;
        protected global::System.Web.UI.WebControls.Label lblPhotoError;
        protected global::System.Web.UI.WebControls.Button btnUpdateProfile;
    }
}
