//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class Display
    {
        protected global::System.Web.UI.WebControls.TextBox txtSearchName;
        protected global::System.Web.UI.WebControls.TextBox txtSearchEmail;
        protected global::System.Web.UI.WebControls.TextBox txtSearchMobile;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterGender;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnExport;
        protected global::System.Web.UI.WebControls.Label lblRecordCount;
        protected global::System.Web.UI.WebControls.GridView gvStudents;
    }
}
