//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class FeeStructureEdit
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.HiddenField hdnFeeStructureId;
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlInstitute;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlYearSemester;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudentCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlFeeType;
        protected global::System.Web.UI.WebControls.TextBox txtFeeAmount;
        protected global::System.Web.UI.WebControls.RangeValidator rvAmount;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDueDate;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.CheckBox chkInstallmentsAllowed;
        protected global::System.Web.UI.WebControls.DropDownList ddlNumberOfInstallments;
        protected global::System.Web.UI.WebControls.Panel pnlInstallments;
        protected global::System.Web.UI.WebControls.Repeater rptInstallments;
        protected global::System.Web.UI.WebControls.DropDownList ddlLateFeeType;
        protected global::System.Web.UI.WebControls.TextBox txtLateFeeValue;
        protected global::System.Web.UI.WebControls.TextBox txtGraceDays;
        protected global::System.Web.UI.WebControls.TextBox txtLateFeeMax;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
