//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class Home
    {
        protected global::System.Web.UI.WebControls.Panel pnlCarousel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl carouselIndicators;
        protected global::System.Web.UI.WebControls.Repeater rptBanners;
        protected global::System.Web.UI.WebControls.Panel pnlCarouselControls;
        protected global::System.Web.UI.WebControls.Panel pnlNoBanners;

        /// <summary>Task 14: registered active candidates carousel.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCandidateCarousel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl candidateIndicators;
        protected global::System.Web.UI.WebControls.Repeater rptCandidateSlides;
        protected global::System.Web.UI.WebControls.Panel pnlCandidateControls;
        protected global::System.Web.UI.WebControls.Panel pnlNoCandidates;
    }
}
