//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class InstituteManagement
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.LinkButton lnkTabPending;
        protected global::System.Web.UI.WebControls.LinkButton lnkTabApproved;
        protected global::System.Web.UI.WebControls.LinkButton lnkTabRejected;
        protected global::System.Web.UI.WebControls.LinkButton lnkTabAll;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.GridView gvInstitutes;

        protected global::System.Web.UI.WebControls.TextBox txtRejectRemark;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRemark;
        protected global::System.Web.UI.WebControls.Button btnConfirmReject;
        protected global::System.Web.UI.WebControls.HiddenField hdnRejectInstituteId;
    }
}
