//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class InstituteRegister
    {
        protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.TextBox txtInstituteName;
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.TextBox txtWebsite;
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;
        protected global::System.Web.UI.WebControls.TextBox txtContactPhone;
        protected global::System.Web.UI.WebControls.TextBox txtCourses;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
