//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class InstituteDashboard
    {
        protected global::System.Web.UI.WebControls.Literal litInstName;
        protected global::System.Web.UI.WebControls.Literal litInstId;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.Literal litInstName2;
        protected global::System.Web.UI.WebControls.Literal litInstId2;
        protected global::System.Web.UI.WebControls.Label lblStatusBadge;
        protected global::System.Web.UI.WebControls.Literal litModuleCount;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyModules;
        protected global::System.Web.UI.WebControls.Repeater rptModules;

        protected global::System.Web.UI.WebControls.Panel pnlNoSelection;
        protected global::System.Web.UI.WebControls.Panel pnlModuleDetail;
        protected global::System.Web.UI.WebControls.Literal litModuleTitle;
        protected global::System.Web.UI.WebControls.Panel pnlModuleNote;
        protected global::System.Web.UI.WebControls.Literal litModuleNote;
        protected global::System.Web.UI.WebControls.Repeater rptStats;
        protected global::System.Web.UI.WebControls.Literal litRecentSectionTitle;
        protected global::System.Web.UI.WebControls.GridView gvRecent;
        protected global::System.Web.UI.WebControls.Panel pnlRecentEmpty;
    }
}
