//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class RecordPayment
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Panel pnlNoStudent;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litStudentName;
        protected global::System.Web.UI.WebControls.Literal litOutstanding;
        protected global::System.Web.UI.WebControls.Literal litNetPayable;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.RangeValidator rvAmount;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaymentMode;
        protected global::System.Web.UI.WebControls.Panel pnlOnlineFields;
        protected global::System.Web.UI.WebControls.TextBox txtGatewayName;
        protected global::System.Web.UI.WebControls.TextBox txtGatewayTxnId;
        protected global::System.Web.UI.WebControls.Panel pnlOfflineFields;
        protected global::System.Web.UI.WebControls.TextBox txtBankRef;
        protected global::System.Web.UI.WebControls.TextBox txtChequeNo;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Button btnRecord;
        protected global::System.Web.UI.WebControls.Panel pnlAllocationResult;
        protected global::System.Web.UI.WebControls.Literal litReceiptNo;
        protected global::System.Web.UI.WebControls.GridView gvAllocations;
    }
}
