//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class Register
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMsg;
        protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
        protected global::System.Web.UI.WebControls.TextBox txtStudentIdPreview;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.TextBox txtDOB;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.HiddenField hdnFullMobile;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnSendOTP;
        protected global::System.Web.UI.WebControls.TextBox txtOTP;
        protected global::System.Web.UI.WebControls.Button btnVerifyOTP;
        protected global::System.Web.UI.WebControls.Button btnResendOTP;
        protected global::System.Web.UI.WebControls.Panel pnlOtpStatus;
        protected global::System.Web.UI.UpdatePanel upLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlCountry;
        protected global::System.Web.UI.WebControls.DropDownList ddlState;
        protected global::System.Web.UI.WebControls.DropDownList ddlDistrict;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.UpdatePanel upAcademic;
        protected global::System.Web.UI.WebControls.DropDownList ddlInstitute;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlYearSemester;
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudentCategory;
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;
        protected global::System.Web.UI.WebControls.Label lblPhotoError;
        protected global::System.Web.UI.WebControls.Label lblVerifiedStatus;
        protected global::System.Web.UI.WebControls.Button btnRegister;
        protected global::System.Web.UI.WebControls.Panel pnlAdBanner;
        protected global::System.Web.UI.WebControls.Panel pnlAdIndicators;
        protected global::System.Web.UI.WebControls.Repeater rptAdIndicators;
        protected global::System.Web.UI.WebControls.Repeater rptAds;
        protected global::System.Web.UI.WebControls.Panel pnlAdControls;
    }
}
