//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class RichTextEditorEdit
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.Literal litBreadcrumb;
        protected global::System.Web.UI.WebControls.HiddenField hdnDocumentId;
        protected global::System.Web.UI.WebControls.Literal litFormHeading;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.TextBox txtContent;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContent;
        protected global::System.Web.UI.WebControls.CustomValidator cvContent;

        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
