//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class RichTextEditor
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.Literal litResultCount;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.GridView gvDocuments;

        protected global::System.Web.UI.WebControls.Literal litPageInfo;
        protected global::System.Web.UI.WebControls.LinkButton btnFirst;
        protected global::System.Web.UI.WebControls.LinkButton btnPrev;
        protected global::System.Web.UI.WebControls.LinkButton btnNext;
        protected global::System.Web.UI.WebControls.LinkButton btnLast;

        protected global::System.Web.UI.WebControls.Literal litViewTitle;
        protected global::System.Web.UI.WebControls.Literal litViewContent;
        protected global::System.Web.UI.WebControls.HiddenField hdnOpenViewModal;
    }
}
