//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class StudentFeeDemand
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.TextBox txtStudentSearch;
        protected global::System.Web.UI.WebControls.Button btnFindStudent;
        protected global::System.Web.UI.WebControls.GridView gvStudentResults;
        protected global::System.Web.UI.WebControls.Panel pnlStudent;
        protected global::System.Web.UI.WebControls.HiddenField hdnStudentId;
        protected global::System.Web.UI.WebControls.Literal litStudentHeader;
        protected global::System.Web.UI.WebControls.HiddenField hdnClear;
        protected global::System.Web.UI.WebControls.DropDownList ddlAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlInstitute;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlYearSemester;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudentCategory;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.Button btnGenerateDemand;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRecordPayment;
        protected global::System.Web.UI.WebControls.Panel pnlSummary;
        protected global::System.Web.UI.WebControls.Literal litTotalPayable;
        protected global::System.Web.UI.WebControls.Literal litAmountPaid;
        protected global::System.Web.UI.WebControls.Literal litOutstanding;
        protected global::System.Web.UI.WebControls.Literal litLateFee;
        protected global::System.Web.UI.WebControls.Literal litDiscount;
        protected global::System.Web.UI.WebControls.Literal litNetPayable;
        protected global::System.Web.UI.WebControls.Literal litPaymentStatus;
        protected global::System.Web.UI.WebControls.GridView gvFeeHeads;
        protected global::System.Web.UI.WebControls.GridView gvTransactions;
    }
}
