//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class TimetableRoomManagement
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.GridView gvRooms;
        protected global::System.Web.UI.WebControls.TextBox txtRoomNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlRoomType;
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;
        protected global::System.Web.UI.WebControls.TextBox txtBuilding;
        protected global::System.Web.UI.WebControls.Button btnAddRoom;
    }
}
