//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class TimetableSetup
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.Panel pnlSchedule;
        protected global::System.Web.UI.WebControls.GridView gvDays;
        protected global::System.Web.UI.WebControls.GridView gvPeriods;
        protected global::System.Web.UI.WebControls.TextBox txtPeriodNum;
        protected global::System.Web.UI.WebControls.TextBox txtPeriodLabel;
        protected global::System.Web.UI.WebControls.TextBox txtPeriodStart;
        protected global::System.Web.UI.WebControls.TextBox txtPeriodEnd;
        protected global::System.Web.UI.WebControls.CheckBox chkPeriodBreak;
        protected global::System.Web.UI.WebControls.Button btnAddPeriod;
        protected global::System.Web.UI.WebControls.TextBox txtMaxPerDay;
        protected global::System.Web.UI.WebControls.Button btnSaveMax;

        protected global::System.Web.UI.WebControls.Panel pnlDivisions;
        protected global::System.Web.UI.WebControls.GridView gvDivisions;
        protected global::System.Web.UI.WebControls.DropDownList ddlDivAcademicYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlDivCourse;
        protected global::System.Web.UI.WebControls.TextBox txtDivYearSem;
        protected global::System.Web.UI.WebControls.TextBox txtDivName;
        protected global::System.Web.UI.WebControls.TextBox txtDivStrength;
        protected global::System.Web.UI.WebControls.Button btnAddDivision;

        protected global::System.Web.UI.WebControls.Panel pnlSubjects;
        protected global::System.Web.UI.WebControls.GridView gvSubjects;
        protected global::System.Web.UI.WebControls.TextBox txtSubCode;
        protected global::System.Web.UI.WebControls.TextBox txtSubName;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubCourse;
        protected global::System.Web.UI.WebControls.TextBox txtSubYearSem;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubType;
        protected global::System.Web.UI.WebControls.TextBox txtSubWeeklyHours;
        protected global::System.Web.UI.WebControls.Button btnAddSubject;
    }
}
