//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class TimetableFacultyEdit
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litFacultyName;

        protected global::System.Web.UI.WebControls.GridView gvAssignments;
        protected global::System.Web.UI.WebControls.DropDownList ddlDivision;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.Button btnAssign;

        protected global::System.Web.UI.WebControls.Literal litAvailabilityGrid;
        protected global::System.Web.UI.WebControls.Button btnSaveAvailability;
        protected global::System.Web.UI.WebControls.Button btnClearAvailability;
    }
}
