//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class TimetableEditor
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litDivisionName;
        protected global::System.Web.UI.WebControls.Literal litGrid;

        protected global::System.Web.UI.WebControls.DropDownList ddlEditEntry;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditDay;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditPeriod;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditFaculty;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditRoom;
        protected global::System.Web.UI.WebControls.Button btnMove;
        protected global::System.Web.UI.WebControls.Literal litMoveResult;

        protected global::System.Web.UI.WebControls.DropDownList ddlSwapA;
        protected global::System.Web.UI.WebControls.DropDownList ddlSwapB;
        protected global::System.Web.UI.WebControls.Button btnSwap;
        protected global::System.Web.UI.WebControls.Literal litSwapResult;
    }
}
