//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistrationSystem
{
    public partial class TimetableRoomEdit
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litRoomName;
        protected global::System.Web.UI.WebControls.Literal litAvailabilityGrid;
        protected global::System.Web.UI.WebControls.Button btnSaveAvailability;
        protected global::System.Web.UI.WebControls.Button btnClearAvailability;
    }
}
